"""Configuration loading and project root detection."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


SHARED_DIR = Path("docs") / "source" / "shared"
CONFIG_FILE = "shared.json"

# .gitignore content for the shared directory:
# ignore everything except the config and .gitignore itself
GITIGNORE_CONTENT = """\
# Auto-generated by tlc-shared-docs
# Ignore all fetched shared files; only track the config
*
!.gitignore
!shared.json
"""


@dataclass
class SourceRepo:
    url: str
    branch: str = "main"


@dataclass
class SharedFile:
    remote_path: str
    local_path: str
    action: str = "get"  # "get" or "push"


@dataclass
class SharedConfig:
    source_repo: SourceRepo
    shared_files: List[SharedFile] = field(default_factory=list)


def find_project_root(start: Optional[Path] = None) -> Path:
    """Walk up from *start* (default: cwd) to find the nearest directory
    that contains a ``.git`` folder, ``pyproject.toml``, or ``setup.py``."""
    current = (start or Path.cwd()).resolve()
    for directory in [current, *current.parents]:
        if any((directory / marker).exists() for marker in (".git", "pyproject.toml", "setup.py")):
            return directory
    raise FileNotFoundError(
        "Could not locate project root (no .git, pyproject.toml, or setup.py found)"
    )


def shared_dir_path(project_root: Path) -> Path:
    return project_root / SHARED_DIR


def config_path(project_root: Path) -> Path:
    return shared_dir_path(project_root) / CONFIG_FILE


def ensure_shared_dir(project_root: Path) -> Path:
    """Create the shared directory and its .gitignore if they don't exist."""
    sdir = shared_dir_path(project_root)
    sdir.mkdir(parents=True, exist_ok=True)

    gitignore = sdir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(GITIGNORE_CONTENT, encoding="utf-8")

    return sdir


def resolve_local_path(project_root: Path, local_path_str: str) -> Path:
    """Resolve a local_path from shared.json.

    - Paths starting with ``/`` are relative to the project root.
    - All other paths are relative to the shared directory.
    """
    if local_path_str.startswith("/"):
        return project_root / local_path_str.lstrip("/")
    return shared_dir_path(project_root) / local_path_str


def load_config(project_root: Path) -> SharedConfig:
    """Read and parse shared.json."""
    cfg_path = config_path(project_root)
    if not cfg_path.exists():
        raise FileNotFoundError(f"Config not found: {cfg_path}")

    data = json.loads(cfg_path.read_text(encoding="utf-8"))

    repo_data = data["source_repo"]
    source_repo = SourceRepo(
        url=repo_data["url"],
        branch=repo_data.get("branch", "main"),
    )

    shared_files: List[SharedFile] = []
    for entry in data.get("shared_files", []):
        shared_files.append(
            SharedFile(
                remote_path=entry["remote_path"],
                local_path=entry["local_path"],
                action=entry.get("action", "get"),
            )
        )

    return SharedConfig(source_repo=source_repo, shared_files=shared_files)
