"""Configuration loading and project root detection."""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


SHARED_DIR = Path("docs") / "source" / "shared"
CONFIG_FILE = "shared.json"
HASHES_FILE = ".shared-hashes.json"
CENTRAL_CONFIG_DIR = ".configs"

# .gitignore content for the shared directory:
# ignore everything except the config and .gitignore itself
GITIGNORE_CONTENT = """\
# Auto-generated by tlc-shared-docs
# Ignore all fetched shared files; only track the config
*
!.gitignore
!shared.json
"""


@dataclass
class SourceRepo:
    url: str
    branch: str = "main"


@dataclass
class SharedFile:
    remote_path: str
    local_path: str
    action: str = "get"  # "get" or "push"


@dataclass
class SharedConfig:
    source_repo: SourceRepo
    shared_files: List[SharedFile] = field(default_factory=list)
    mode: str = "local"  # "local" or "central"


_GLOB_CHARS = set("*?[")


def is_glob(path: str) -> bool:
    """Return True if *path* contains glob wildcard characters."""
    return bool(_GLOB_CHARS & set(path))


def glob_prefix(pattern: str) -> str:
    """Return the non-glob prefix of a pattern.

    For ``stories/**/*.md`` this returns ``stories``.
    For ``*.md`` this returns an empty string.
    """
    parts = pattern.replace("\\", "/").split("/")
    prefix_parts = []
    for p in parts:
        if _GLOB_CHARS & set(p):
            break
        prefix_parts.append(p)
    return "/".join(prefix_parts)


def find_project_root(start: Optional[Path] = None) -> Path:
    """Walk up from *start* (default: cwd) to find the nearest directory
    that contains a ``.git`` folder, ``pyproject.toml``, or ``setup.py``."""
    current = (start or Path.cwd()).resolve()
    for directory in [current, *current.parents]:
        if any((directory / marker).exists() for marker in (".git", "pyproject.toml", "setup.py")):
            return directory
    raise FileNotFoundError(
        "Could not locate project root (no .git, pyproject.toml, or setup.py found)"
    )


def shared_dir_path(project_root: Path) -> Path:
    return project_root / SHARED_DIR


def config_path(project_root: Path) -> Path:
    return shared_dir_path(project_root) / CONFIG_FILE


def ensure_shared_dir(project_root: Path) -> Path:
    """Create the shared directory and its .gitignore if they don't exist."""
    sdir = shared_dir_path(project_root)
    sdir.mkdir(parents=True, exist_ok=True)

    gitignore = sdir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(GITIGNORE_CONTENT, encoding="utf-8")

    return sdir


def hashes_path(project_root: Path) -> Path:
    return shared_dir_path(project_root) / HASHES_FILE


def load_hashes(project_root: Path) -> dict[str, str]:
    """Load the stored ``{remote_path: blob_sha}`` mapping.

    Returns an empty dict if the file doesn't exist.
    """
    hp = hashes_path(project_root)
    if not hp.exists():
        return {}
    try:
        return json.loads(hp.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def save_hashes(project_root: Path, hashes: dict[str, str]) -> None:
    """Persist the ``{remote_path: blob_sha}`` mapping."""
    hp = hashes_path(project_root)
    hp.write_text(json.dumps(hashes, indent=2) + "\n", encoding="utf-8")


def resolve_local_path(project_root: Path, local_path_str: str) -> Path:
    """Resolve a local_path from shared.json.

    - Paths starting with ``/`` are relative to the project root.
    - All other paths are relative to the shared directory.
    """
    if local_path_str.startswith("/"):
        return project_root / local_path_str.lstrip("/")
    return shared_dir_path(project_root) / local_path_str


def extract_org_repo(url: str) -> str:
    """Extract ``org/repo`` from a Git URL (HTTPS or SSH).

    Handles:
    - ``https://github.com/org/repo.git``
    - ``https://github.com/org/repo``
    - ``git@github.com:org/repo.git``
    - ``ssh://git@github.com/org/repo.git``
    """
    # Strip trailing .git
    url = url.rstrip("/")
    if url.endswith(".git"):
        url = url[:-4]

    # SSH shorthand: git@host:org/repo
    m = re.match(r"^[\w.-]+@[\w.-]+:(.*)", url)
    if m:
        return m.group(1)

    # HTTPS / SSH-URL: extract last two path segments
    m = re.search(r"/([\w._-]+/[\w._-]+)$", url)
    if m:
        return m.group(1)

    raise ValueError(f"Cannot extract org/repo from URL: {url}")


def detect_repo_identity(project_root: Path) -> str:
    """Detect the current repo's ``org/repo`` from its git remote origin."""
    try:
        from git import Repo, InvalidGitRepositoryError
        repo = Repo(project_root)
        origin_url = repo.remotes.origin.url
        return extract_org_repo(origin_url)
    except Exception as exc:
        raise RuntimeError(
            f"Cannot detect repo identity from {project_root}: {exc}"
        ) from exc


def central_config_path(org_repo: str) -> str:
    """Return the path inside the source repo where the central config lives.

    Example: ``org/repo`` -> ``.configs/org/repo.json``
    """
    return f"{CENTRAL_CONFIG_DIR}/{org_repo}.json"


def parse_shared_files(data: dict) -> List[SharedFile]:
    """Parse the shared_files list from a config dict."""
    shared_files: List[SharedFile] = []
    for entry in data.get("shared_files", []):
        shared_files.append(
            SharedFile(
                remote_path=entry["remote_path"],
                local_path=entry["local_path"],
                action=entry.get("action", "get"),
            )
        )
    return shared_files


def load_config(project_root: Path) -> SharedConfig:
    """Read and parse shared.json."""
    cfg_path = config_path(project_root)
    if not cfg_path.exists():
        raise FileNotFoundError(f"Config not found: {cfg_path}")

    data = json.loads(cfg_path.read_text(encoding="utf-8"))

    repo_data = data["source_repo"]
    source_repo = SourceRepo(
        url=repo_data["url"],
        branch=repo_data.get("branch", "main"),
    )

    mode = data.get("mode", "local")
    shared_files = parse_shared_files(data)

    return SharedConfig(
        source_repo=source_repo,
        shared_files=shared_files,
        mode=mode,
    )
