"""Configuration loading and project root detection."""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


logger = logging.getLogger(__name__)

SHARED_DIR = Path("docs") / "source" / "shared"
CONFIG_FILE = "shared.json"
HASHES_FILE = ".shared-hashes.json"
CENTRAL_CONFIG_DIR = ".configs"

# .gitignore content for the shared directory:
# ignore everything except the config and .gitignore itself
GITIGNORE_CONTENT = """\
# Auto-generated by tlc-shared-docs
# Ignore all fetched shared files; only track the config
*
!.gitignore
!shared.json
"""


@dataclass
class SourceRepo:
    url: str
    branch: str = "main"


@dataclass
class SharedFile:
    remote_path: str
    local_path: str
    action: str = "get"  # "get" or "push"


@dataclass
class UploadConfig:
    """Controls auto-upload of new local files to the shared repo."""
    allowed: bool = False
    paths: List[str] = field(default_factory=list)  # fnmatch patterns


@dataclass
class SharedConfig:
    source_repo: SourceRepo
    shared_files: List[SharedFile] = field(default_factory=list)
    mode: str = "local"  # "local" or "central"
    uploads: Optional[UploadConfig] = None


_GLOB_CHARS = set("*?[")


def glob_match(path: str, pattern: str) -> bool:
    """Match *path* against a glob *pattern* supporting ``**`` recursion.

    ``fnmatch`` doesn't handle ``**`` as recursive, so we convert the
    pattern to a regex where ``**/`` matches zero or more directory levels.
    """
    regex = re.escape(pattern)
    # re.escape turns * into \*, ** into \*\*
    regex = regex.replace(r"\*\*/", "<<GLOBSTAR_SLASH>>")
    regex = regex.replace(r"\*\*", "<<GLOBSTAR>>")
    regex = regex.replace(r"\*", r"[^/]*")
    regex = regex.replace(r"\?", r"[^/]")
    regex = regex.replace("<<GLOBSTAR_SLASH>>", r"([^/]+/)*")
    regex = regex.replace("<<GLOBSTAR>>", r".*")
    return bool(re.fullmatch(regex, path))


def is_glob(path: str) -> bool:
    """Return True if *path* contains glob wildcard characters."""
    return bool(_GLOB_CHARS & set(path))


def glob_prefix(pattern: str) -> str:
    """Return the non-glob prefix of a pattern.

    For ``stories/**/*.md`` this returns ``stories``.
    For ``*.md`` this returns an empty string.
    """
    # Split on forward slashes and collect segments until we hit a glob char
    parts = pattern.replace("\\", "/").split("/")
    prefix_parts = []
    for p in parts:
        if _GLOB_CHARS & set(p):
            break
        prefix_parts.append(p)
    return "/".join(prefix_parts)


def find_project_root(start: Optional[Path] = None) -> Path:
    """Walk up from *start* (default: cwd) to find the nearest directory
    that contains a ``.git`` folder, ``pyproject.toml``, or ``setup.py``."""
    current = (start or Path.cwd()).resolve()
    for directory in [current, *current.parents]:
        if any((directory / marker).exists() for marker in (".git", "pyproject.toml", "setup.py")):
            return directory
    raise FileNotFoundError(
        "Could not locate project root (no .git, pyproject.toml, or setup.py found)"
    )


def shared_dir_path(project_root: Path) -> Path:
    """Return the shared directory path for the given project root."""
    return project_root / SHARED_DIR


def config_path(project_root: Path) -> Path:
    """Return the shared.json config path for the given project root."""
    return shared_dir_path(project_root) / CONFIG_FILE


def hashes_path(project_root: Path) -> Path:
    """Return the .shared-hashes.json path for the given project root."""
    return shared_dir_path(project_root) / HASHES_FILE


def ensure_shared_dir(project_root: Path) -> Path:
    """Create the shared directory and its .gitignore if they don't exist."""
    sdir = shared_dir_path(project_root)
    sdir.mkdir(parents=True, exist_ok=True)

    # Write .gitignore to keep fetched docs out of version control
    gitignore = sdir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(GITIGNORE_CONTENT, encoding="utf-8")

    return sdir


def load_hashes(project_root: Path) -> dict[str, str]:
    """Load the stored ``{remote_path: blob_sha}`` mapping.

    Returns an empty dict if the file doesn't exist or is corrupt.
    """
    hp = hashes_path(project_root)
    if not hp.exists():
        return {}
    try:
        return json.loads(hp.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Failed to load hashes from %s: %s", hp, exc)
        return {}


def save_hashes(project_root: Path, hashes: dict[str, str]) -> None:
    """Persist the ``{remote_path: blob_sha}`` mapping."""
    hp = hashes_path(project_root)
    hp.write_text(json.dumps(hashes, indent=2) + "\n", encoding="utf-8")


def resolve_local_path(project_root: Path, local_path_str: str) -> Path:
    """Resolve a local_path from shared.json.

    - Paths starting with ``/`` are relative to the project root.
    - All other paths are relative to the shared directory.
    """
    if local_path_str.startswith("/"):
        return project_root / local_path_str.lstrip("/")
    return shared_dir_path(project_root) / local_path_str


def extract_org_repo(url: str) -> str:
    """Extract ``org/repo`` from a Git URL (HTTPS or SSH).

    Handles HTTPS, SSH shorthand (git@host:org/repo), and
    full SSH URLs (ssh://git@host/org/repo). Strips trailing .git.
    """
    url = url.rstrip("/")
    if url.endswith(".git"):
        url = url[:-4]

    # SSH shorthand: git@host:org/repo
    m = re.match(r"^[\w.-]+@[\w.-]+:(.*)", url)
    if m:
        return m.group(1)

    # HTTPS / SSH-URL: extract last two path segments
    m = re.search(r"/([\w._-]+/[\w._-]+)$", url)
    if m:
        return m.group(1)

    raise ValueError(f"Cannot extract org/repo from URL: {url}")


def detect_repo_identity(project_root: Path) -> str:
    """Detect the current repo's ``org/repo`` from its git remote origin."""
    try:
        from git import Repo
        repo = Repo(project_root)
        origin_url = repo.remotes.origin.url
        return extract_org_repo(origin_url)
    except Exception as exc:
        raise RuntimeError(
            f"Cannot detect repo identity from {project_root}: {exc}"
        ) from exc


def central_config_path(org_repo: str) -> str:
    """Return the path inside the source repo where the central config lives.

    Example: ``org/repo`` -> ``.configs/org/repo.json``
    """
    return f"{CENTRAL_CONFIG_DIR}/{org_repo}.json"


def parse_shared_files(data: dict) -> List[SharedFile]:
    """Parse the shared_files list from a config dict."""
    shared_files: List[SharedFile] = []
    for entry in data.get("shared_files", []):
        shared_files.append(
            SharedFile(
                remote_path=entry["remote_path"],
                local_path=entry["local_path"],
                action=entry.get("action", "get"),
            )
        )
    return shared_files


def parse_upload_config(data: dict) -> Optional[UploadConfig]:
    """Parse the ``uploads`` section from a config dict.

    Returns ``None`` if the section is absent or uploads are disabled.
    """
    uploads_data = data.get("uploads")
    if not uploads_data:
        return None
    return UploadConfig(
        allowed=uploads_data.get("allowed", False),
        paths=uploads_data.get("paths", []),
    )


# Only allow characters safe for directory names on all platforms
_VALID_PROJECT_NAME = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9._-]*$")


def validate_project_name(name: str) -> None:
    """Raise ``ValueError`` if *name* is not a valid folder name.

    Allows alphanumerics, hyphens, underscores, and dots.
    Must start with an alphanumeric character.
    """
    if not _VALID_PROJECT_NAME.match(name):
        raise ValueError(
            f"Invalid project name '{name}'. "
            f"Must match [a-zA-Z0-9][a-zA-Z0-9._-]* "
            f"(alphanumerics, hyphens, underscores, dots; "
            f"must start with a letter or digit)."
        )


def _prefix_local_paths(conf: SharedConfig, project_name: str) -> SharedConfig:
    """Prefix every ``local_path`` in *conf* with *project_name/*.

    Absolute paths (starting with ``/``) are left unchanged since
    they resolve from the project root, not the shared directory.
    """
    prefixed: List[SharedFile] = []
    for sf in conf.shared_files:
        if sf.local_path.startswith("/"):
            prefixed.append(sf)
        else:
            prefixed.append(SharedFile(
                remote_path=sf.remote_path,
                local_path=f"{project_name}/{sf.local_path}",
                action=sf.action,
            ))
    return SharedConfig(
        source_repo=conf.source_repo,
        shared_files=prefixed,
        mode=conf.mode,
        uploads=conf.uploads,
    )


def _parse_project_entry(data: dict) -> SharedConfig:
    """Parse a single project entry (or legacy root) into a SharedConfig."""
    repo_data = data["source_repo"]
    source_repo = SourceRepo(
        url=repo_data["url"],
        branch=repo_data.get("branch", "main"),
    )
    return SharedConfig(
        source_repo=source_repo,
        shared_files=parse_shared_files(data),
        mode=data.get("mode", "local"),
        uploads=parse_upload_config(data),
    )


def list_projects(project_root: Path) -> List[dict[str, str]]:
    """Return summary info for each project in a multi-project config.

    Each entry is ``{"name": ..., "url": ..., "branch": ..., "mode": ...}``.
    Returns an empty list for legacy single-source configs.
    """
    cfg_path = config_path(project_root)
    if not cfg_path.exists():
        raise FileNotFoundError(f"Config not found: {cfg_path}")

    data = json.loads(cfg_path.read_text(encoding="utf-8"))

    if "projects" not in data:
        return []

    default = data.get("default_project", "")
    result: List[dict[str, str]] = []
    for name, entry in sorted(data["projects"].items()):
        repo = entry.get("source_repo", {})
        marker = " (default)" if name == default else ""
        result.append({
            "name": f"{name}{marker}",
            "url": repo.get("url", ""),
            "branch": repo.get("branch", "main"),
            "mode": entry.get("mode", "local"),
        })
    return result


def load_config(project_root: Path, project: Optional[str] = None) -> SharedConfig:
    """Read and parse shared.json from the project's shared directory.

    Supports two formats:

    - **Legacy** (single source): ``{"source_repo": {...}, ...}``
    - **Multi-project**: ``{"projects": {"name": {...}, ...}, "default_project": "name"}``

    When using multi-project format, *project* selects which entry to use.
    Falls back to ``default_project`` if *project* is ``None``.

    In multi-project mode, all relative ``local_path`` values are
    automatically prefixed with the project name to isolate each
    project's files into its own subdirectory.
    """
    cfg_path = config_path(project_root)
    if not cfg_path.exists():
        raise FileNotFoundError(f"Config not found: {cfg_path}")

    data = json.loads(cfg_path.read_text(encoding="utf-8"))

    # Multi-project format: {"projects": {...}}
    if "projects" in data:
        projects = data["projects"]

        # Validate all project names upfront
        for name in projects:
            validate_project_name(name)

        chosen = project or data.get("default_project")

        if not chosen:
            available = ", ".join(sorted(projects.keys()))
            raise ValueError(
                f"No --project specified and no default_project set. "
                f"Available projects: {available}"
            )

        if chosen not in projects:
            available = ", ".join(sorted(projects.keys()))
            raise ValueError(
                f"Project '{chosen}' not found. Available projects: {available}"
            )

        conf = _parse_project_entry(projects[chosen])
        return _prefix_local_paths(conf, chosen)

    # Legacy single-source format
    return _parse_project_entry(data)
